# Generated by Django 4.0.5 on 2022-07-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
